### ISSUE TITLE
authentication rejected, but nothing shows in tcpdump

### ISSUE THREAD

**Issue by beppe9000** [zendframework/zend-mail#241]
I am having this issue... the most similar thing seems to be #170 but in my case tcpdump does not show anything... yet there is a smtp protocol error.

I am using [espocrm](https://github.com/espocrm/espocrm/blob/fe635064d5df63b90853daf7337e5788e3a975c1/application/Espo/Core/Mail/Sender.php#L180)

This is my stack trace. Looks like bad credentials but webmail login works ok in cpanel...

```
Zend\Mail\Protocol\Exception\RuntimeException: 5.7.0 ...authentication rejected
 in /home/foo/public_html/crm/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:348
Stack trace:
#0 /home/foo/public_html/crm/vendor/zendframework/zend-mail/src/Protocol/Smtp/Auth/Login.php(78): Zend\Mail\Protocol\AbstractProtocol->_expect(Array)
#1 /home/foo/public_html/crm/vendor/zendframework/zend-mail/src/Protocol/Smtp.php(222): Zend\Mail\Protocol\Smtp\Auth\Login->auth()
#2 /home/foo/public_html/crm/vendor/zendframework/zend-mail/src/Transport/Smtp.php(401): Zend\Mail\Protocol\Smtp->helo('vps.me.com')
#3 /home/foo/public_html/crm/vendor/zendframework/zend-mail/src/Transport/Smtp.php(383): Zend\Mail\Transport\Smtp->connect()
#4 /home/foo/public_html/crm/vendor/zendframework/zend-mail/src/Transport/Smtp.php(394): Zend\Mail\Transport\Smtp->lazyLoadConnection()
#5 /home/foo/public_html/crm/vendor/zendframework/zend-mail/src/Transport/Smtp.php(251): Zend\Mail\Transport\Smtp->connect()
#6 /home/foo/public_html/crm/application/Espo/Core/Mail/Sender.php(397): Zend\Mail\Transport\Smtp->send(Object(Zend\Mail\Message))
#7 /home/foo/public_html/crm/custom/Espo/Custom/Services/Email.php(116): Espo\Core\Mail\Sender->send(Object(Espo\Entities\Email), Array, Object(Zend\Mail\Message))
#8 /home/foo/public_html/crm/application/Espo/Services/Email.php(324): Espo\Custom\Services\Email->send(Object(Espo\Entities\Email))
```
```

**Comment by weierophinney** [comment]
This repository has been closed and moved to laminas/laminas-mail; a new issue has been opened at https://github.com/laminas/laminas-mail/issues/10.
