### ISSUE TITLE
UTF8 when Read from IMAP

### ISSUE THREAD

**Issue by minhvn** [zendframework/zend-mail#29]
I see error when mail have format with UTF8 Võ Ngọc, Minh <EMAIL>

Exception: exception 'Zend\Mail\Exception\InvalidArgumentException' with message 'The input is not a valid email address. Use the basic format local-part@hostname' in /mdata/libraries/ZendFramework2/library/Zend/Mail/Address.php:41 Stack trace: #0 /mdata/libraries/ZendFramework2/library/Zend/Mail/AddressList.php(249): Zend\Mail\Address->__construct('Nguy\xC3\xAA\xCC\x83n L\xC6\xB0u ...', NULL) #1 /mdata/libraries/ZendFramework2/library/Zend/Mail/AddressList.php(35): Zend\Mail\AddressList->createAddress('Nguy\xC3\xAA\xCC\x83n L\xC6\xB0u ...', NULL) #2 /mdata/libraries/ZendFramework2/library/Zend/Mail/AddressList.php(113): Zend\Mail\AddressList->add('Nguy\xC3\xAA\xCC\x83n L\xC6\xB0u ...', NULL) #3 /mdata/libraries/ZendFramework2/library/Zend/Mail/Header/AbstractAddressList.php(74): Zend\Mail\AddressList->addFromString('Nguy\xC3\xAA\xCC\x83n L\xC6\xB0u ...') #4 /mdata/libraries/ZendFramework2/library/Zend/Mail/Headers.php(479): Zend\Mail\Header\AbstractAddressList::fromString('From: =?UTF-8?Q...') #5 /mdata/libraries/ZendFramework2/library/Zend/Mail/Headers.php(314): Zend\Mail\Headers->lazyLoadHeader(14) #6 /mdata/libraries/ZendFramework2/library/Zend/Mail/Storage/Part.php(291): Zend\Mail\Headers->get('from') #7 /mdata/libraries/ZendFramework2/library/Zend/Mail/Storage/Part.php(365): Zend\Mail\Storage\Part->getHeader('from', 'string') #8

Thank you very much.

**Comment by michalbundyra** [comment]
This repository has been closed and moved to laminas/laminas-mail; a new issue has been opened at https://github.com/laminas/laminas-mail/issues/71.
