### ISSUE TITLE
Zend Mail Pop3 - Invalid header value detected

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-mail#97]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

___
Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7655
User: @stmaxvl
Created On: 2015-12-28T12:01:52Z
Updated At: 2016-02-13T15:34:07Z
Body
I use Zend\Mail\Storage\Pop3 to get message.
ZF Version 2.5.1

Code:

$mail = new \Zend\Mail\Storage\Pop3(
    			array(
    			'host'     => '...',
    			'user'     => '...',
    			'password' => '...',
    			'ssl'      => 'SSL'
    	));
    		$count = $mail->countMessages();
     		for($messageNum=1; $messageNum<=$count; $messageNum++){
	     			$message = $mail->getMessage($messageNum);
               }

Trace error:

Invalid header value detected#0 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Header\GenericHeader.php(35): Zend\Mail\Header\GenericHeader::splitHeaderLine('Subject: \xD0\x9E\xD1\x84\xD0\xBB...')
#1 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Headers.php(231): Zend\Mail\Header\GenericHeader::fromString('Subject: \xD0\x9E\xD1\x84\xD0\xBB...')
#2 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Headers.php(95): Zend\Mail\Headers->addHeaderLine('Subject: \xD0\x9E\xD1\x84\xD0\xBB...')
#3 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Storage\Part.php(108): Zend\Mail\Headers::fromString('X-Yandex-Folder...')
#4 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Storage\Message.php(54): Zend\Mail\Storage\Part->__construct(Array)
#5 C:\xampp\htdocs\master4u\vendor\zendframework\zend-mail\src\Storage\Pop3.php(65): Zend\Mail\Storage\Message->__construct(Array)
#6 C:\xampp\htdocs\master4u\module\PpModuleMailer\src\PpModuleMailer\Controller\ConsoleController.php(82): Zend\Mail\Storage\Pop3->getMessage(1)

___

**Comment by nickel715** [comment]
I have the same problem, I'm also using `\Zend\Mail\Storage\Message`. 
Some of my incoming emails containing non ASCII characters in header values, especially in subject :(

I tried to disable the validation but I failed because the validation is hard wired and deep nested in the parse logic.

At the moment i've no idea how to solve this problem. Does anyone have an idea?

**Comment by michalbundyra** [comment]
This repository has been closed and moved to laminas/laminas-mail; a new issue has been opened at https://github.com/laminas/laminas-mail/issues/58.
